name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-ci:
    name: Frontend CI
    uses: ./.github/workflows/frontend-ci.yml

  backend-ci:
    name: Backend CI
    uses: ./.github/workflows/backend-ci.yml
